# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TwilioTest' do
    #pod "SlackTextViewController"
end

target 'TwilioTestTests' do

end

target 'TwilioTestUITests' do

end

